<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PackageId>FMGame.Scenes</PackageId>
    <Title>FMGame.Scenes</Title>
    <AssemblyName>$(Title)</AssemblyName>
    <Version>1.0.0</Version>
    <Authors>Pdani</Authors>
    <Product>$(Title)</Product>
    <Description>Game screens (aka scenes) in Fazbear Multiplayer</Description>
    <Copyright>$(Authors)</Copyright>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
    <RootNamespace>ReFMGame.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Animations\Animations.csproj" />
  </ItemGroup>

</Project>
